# environment_system_cuda.yml
# Uses system CUDA 12.5 instead of conda CUDA packages

name: biogpu
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  # Python version
  - python=3.13

  # GPU Python packages that work with system CUDA
  # - cupy-cuda12x        # Auto-detects CUDA 12.x
  - numba>=0.58         # Uses system CUDA
  - cuda-python>=12.0   # Python bindings
  
  # Compilers and build tools (no CUDA compiler from conda)
  - gxx_linux-64=11.*   # C++ compiler
  - cmake>=3.26
  - ninja
  - make
  - pkg-config
  
  # Bioinformatics tools
  - biopython=1.83
  - pysam=0.22
  - samtools=1.19
  - minimap2=2.26
  - bwa=0.7.17
  - bedtools=2.31
  
  # Scientific computing
  - numpy=1.26.*
  - scipy=1.11.*
  - pandas=2.1.*
  - scikit-learn=1.3.*
  - matplotlib=3.8.*
  - seaborn=0.13.*
  
  # Development tools
  - ipython
  - jupyter
  - jupyterlab=4.*
  - pytest=7.4.*
  - pytest-benchmark
  - black=23.*
  - ruff  # Fast Python linter
  - cython=3.0.*
  
  # Profiling
  - line_profiler
  - memory_profiler
  - py-spy
  
  # Documentation
  - sphinx
  - sphinx_rtd_theme
  
  # Utilities
  - click=8.1.*
  - rich=13.*
  - tqdm
  - pyyaml
  - h5py
  - zarr  # Alternative to HDF5
  
  # Parallel processing
  - dask
  - joblib
  
  # Pip packages not in conda
  - pip
  - pip:
    - pycuda>=2024.1
    - gpustat
    - nvidia-ml-py
    - biobear  # Fast bio file parsing