# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/david/Documents/Code/biogpu

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/david/Documents/Code/biogpu

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/david/Documents/Code/biogpu/CMakeFiles /home/david/Documents/Code/biogpu//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/david/Documents/Code/biogpu/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named build_clean_resistance_db

# Build rule for target.
build_clean_resistance_db: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 build_clean_resistance_db
.PHONY : build_clean_resistance_db

# fast build rule for target.
build_clean_resistance_db/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build_clean_resistance_db.dir/build.make CMakeFiles/build_clean_resistance_db.dir/build
.PHONY : build_clean_resistance_db/fast

#=============================================================================
# Target rules for targets named build_integrated_resistance_db

# Build rule for target.
build_integrated_resistance_db: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 build_integrated_resistance_db
.PHONY : build_integrated_resistance_db

# fast build rule for target.
build_integrated_resistance_db/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build_integrated_resistance_db.dir/build.make CMakeFiles/build_integrated_resistance_db.dir/build
.PHONY : build_integrated_resistance_db/fast

#=============================================================================
# Target rules for targets named build_nucleotide_index

# Build rule for target.
build_nucleotide_index: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 build_nucleotide_index
.PHONY : build_nucleotide_index

# fast build rule for target.
build_nucleotide_index/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build_nucleotide_index.dir/build.make CMakeFiles/build_nucleotide_index.dir/build
.PHONY : build_nucleotide_index/fast

#=============================================================================
# Target rules for targets named build_protein_index

# Build rule for target.
build_protein_index: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 build_protein_index
.PHONY : build_protein_index

# fast build rule for target.
build_protein_index/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build_protein_index.dir/build.make CMakeFiles/build_protein_index.dir/build
.PHONY : build_protein_index/fast

#=============================================================================
# Target rules for targets named build_resistance_catalog

# Build rule for target.
build_resistance_catalog: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 build_resistance_catalog
.PHONY : build_resistance_catalog

# fast build rule for target.
build_resistance_catalog/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build_resistance_catalog.dir/build.make CMakeFiles/build_resistance_catalog.dir/build
.PHONY : build_resistance_catalog/fast

#=============================================================================
# Target rules for targets named validate_fq_database

# Build rule for target.
validate_fq_database: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 validate_fq_database
.PHONY : validate_fq_database

# fast build rule for target.
validate_fq_database/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/validate_fq_database.dir/build.make CMakeFiles/validate_fq_database.dir/build
.PHONY : validate_fq_database/fast

#=============================================================================
# Target rules for targets named test_clean_pipeline

# Build rule for target.
test_clean_pipeline: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_clean_pipeline
.PHONY : test_clean_pipeline

# fast build rule for target.
test_clean_pipeline/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_clean_pipeline.dir/build.make CMakeFiles/test_clean_pipeline.dir/build
.PHONY : test_clean_pipeline/fast

#=============================================================================
# Target rules for targets named validate_integrated_db

# Build rule for target.
validate_integrated_db: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 validate_integrated_db
.PHONY : validate_integrated_db

# fast build rule for target.
validate_integrated_db/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/validate_integrated_db.dir/build.make CMakeFiles/validate_integrated_db.dir/build
.PHONY : validate_integrated_db/fast

#=============================================================================
# Target rules for targets named test_integrated_pipeline

# Build rule for target.
test_integrated_pipeline: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_integrated_pipeline
.PHONY : test_integrated_pipeline

# fast build rule for target.
test_integrated_pipeline/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_integrated_pipeline.dir/build.make CMakeFiles/test_integrated_pipeline.dir/build
.PHONY : test_integrated_pipeline/fast

#=============================================================================
# Target rules for targets named benchmark_integrated

# Build rule for target.
benchmark_integrated: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 benchmark_integrated
.PHONY : benchmark_integrated

# fast build rule for target.
benchmark_integrated/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark_integrated.dir/build.make CMakeFiles/benchmark_integrated.dir/build
.PHONY : benchmark_integrated/fast

#=============================================================================
# Target rules for targets named analyze_resistance_profile

# Build rule for target.
analyze_resistance_profile: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 analyze_resistance_profile
.PHONY : analyze_resistance_profile

# fast build rule for target.
analyze_resistance_profile/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/analyze_resistance_profile.dir/build.make CMakeFiles/analyze_resistance_profile.dir/build
.PHONY : analyze_resistance_profile/fast

#=============================================================================
# Target rules for targets named clinical_interpretation

# Build rule for target.
clinical_interpretation: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clinical_interpretation
.PHONY : clinical_interpretation

# fast build rule for target.
clinical_interpretation/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clinical_interpretation.dir/build.make CMakeFiles/clinical_interpretation.dir/build
.PHONY : clinical_interpretation/fast

#=============================================================================
# Target rules for targets named sample_csv_parser

# Build rule for target.
sample_csv_parser: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sample_csv_parser
.PHONY : sample_csv_parser

# fast build rule for target.
sample_csv_parser/fast:
	$(MAKE) $(MAKESILENT) -f runtime/kernels/resistance/CMakeFiles/sample_csv_parser.dir/build.make runtime/kernels/resistance/CMakeFiles/sample_csv_parser.dir/build
.PHONY : sample_csv_parser/fast

#=============================================================================
# Target rules for targets named bloom_filter

# Build rule for target.
bloom_filter: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bloom_filter
.PHONY : bloom_filter

# fast build rule for target.
bloom_filter/fast:
	$(MAKE) $(MAKESILENT) -f runtime/kernels/resistance/CMakeFiles/bloom_filter.dir/build.make runtime/kernels/resistance/CMakeFiles/bloom_filter.dir/build
.PHONY : bloom_filter/fast

#=============================================================================
# Target rules for targets named hdf5_writer

# Build rule for target.
hdf5_writer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hdf5_writer
.PHONY : hdf5_writer

# fast build rule for target.
hdf5_writer/fast:
	$(MAKE) $(MAKESILENT) -f runtime/kernels/resistance/CMakeFiles/hdf5_writer.dir/build.make runtime/kernels/resistance/CMakeFiles/hdf5_writer.dir/build
.PHONY : hdf5_writer/fast

#=============================================================================
# Target rules for targets named translated_search

# Build rule for target.
translated_search: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 translated_search
.PHONY : translated_search

# fast build rule for target.
translated_search/fast:
	$(MAKE) $(MAKESILENT) -f runtime/kernels/resistance/CMakeFiles/translated_search.dir/build.make runtime/kernels/resistance/CMakeFiles/translated_search.dir/build
.PHONY : translated_search/fast

#=============================================================================
# Target rules for targets named kmer_screening

# Build rule for target.
kmer_screening: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kmer_screening
.PHONY : kmer_screening

# fast build rule for target.
kmer_screening/fast:
	$(MAKE) $(MAKESILENT) -f runtime/kernels/resistance/CMakeFiles/kmer_screening.dir/build.make runtime/kernels/resistance/CMakeFiles/kmer_screening.dir/build
.PHONY : kmer_screening/fast

#=============================================================================
# Target rules for targets named diagnostic_reporter

# Build rule for target.
diagnostic_reporter: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 diagnostic_reporter
.PHONY : diagnostic_reporter

# fast build rule for target.
diagnostic_reporter/fast:
	$(MAKE) $(MAKESILENT) -f runtime/kernels/resistance/CMakeFiles/diagnostic_reporter.dir/build.make runtime/kernels/resistance/CMakeFiles/diagnostic_reporter.dir/build
.PHONY : diagnostic_reporter/fast

#=============================================================================
# Target rules for targets named global_fq_mapper

# Build rule for target.
global_fq_mapper: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 global_fq_mapper
.PHONY : global_fq_mapper

# fast build rule for target.
global_fq_mapper/fast:
	$(MAKE) $(MAKESILENT) -f runtime/kernels/resistance/CMakeFiles/global_fq_mapper.dir/build.make runtime/kernels/resistance/CMakeFiles/global_fq_mapper.dir/build
.PHONY : global_fq_mapper/fast

#=============================================================================
# Target rules for targets named enhanced_mutation_detection

# Build rule for target.
enhanced_mutation_detection: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 enhanced_mutation_detection
.PHONY : enhanced_mutation_detection

# fast build rule for target.
enhanced_mutation_detection/fast:
	$(MAKE) $(MAKESILENT) -f runtime/kernels/resistance/CMakeFiles/enhanced_mutation_detection.dir/build.make runtime/kernels/resistance/CMakeFiles/enhanced_mutation_detection.dir/build
.PHONY : enhanced_mutation_detection/fast

#=============================================================================
# Target rules for targets named clean_resistance_loader

# Build rule for target.
clean_resistance_loader: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean_resistance_loader
.PHONY : clean_resistance_loader

# fast build rule for target.
clean_resistance_loader/fast:
	$(MAKE) $(MAKESILENT) -f runtime/kernels/resistance/CMakeFiles/clean_resistance_loader.dir/build.make runtime/kernels/resistance/CMakeFiles/clean_resistance_loader.dir/build
.PHONY : clean_resistance_loader/fast

#=============================================================================
# Target rules for targets named resistance_detection_gpu

# Build rule for target.
resistance_detection_gpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 resistance_detection_gpu
.PHONY : resistance_detection_gpu

# fast build rule for target.
resistance_detection_gpu/fast:
	$(MAKE) $(MAKESILENT) -f runtime/kernels/resistance/CMakeFiles/resistance_detection_gpu.dir/build.make runtime/kernels/resistance/CMakeFiles/resistance_detection_gpu.dir/build
.PHONY : resistance_detection_gpu/fast

#=============================================================================
# Target rules for targets named fixed_database_loader

# Build rule for target.
fixed_database_loader: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fixed_database_loader
.PHONY : fixed_database_loader

# fast build rule for target.
fixed_database_loader/fast:
	$(MAKE) $(MAKESILENT) -f runtime/kernels/resistance/CMakeFiles/fixed_database_loader.dir/build.make runtime/kernels/resistance/CMakeFiles/fixed_database_loader.dir/build
.PHONY : fixed_database_loader/fast

#=============================================================================
# Target rules for targets named fq_pipeline_gpu

# Build rule for target.
fq_pipeline_gpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fq_pipeline_gpu
.PHONY : fq_pipeline_gpu

# fast build rule for target.
fq_pipeline_gpu/fast:
	$(MAKE) $(MAKESILENT) -f runtime/kernels/resistance/CMakeFiles/fq_pipeline_gpu.dir/build.make runtime/kernels/resistance/CMakeFiles/fq_pipeline_gpu.dir/build
.PHONY : fq_pipeline_gpu/fast

#=============================================================================
# Target rules for targets named integrated_resistance_pipeline

# Build rule for target.
integrated_resistance_pipeline: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 integrated_resistance_pipeline
.PHONY : integrated_resistance_pipeline

# fast build rule for target.
integrated_resistance_pipeline/fast:
	$(MAKE) $(MAKESILENT) -f runtime/kernels/resistance/CMakeFiles/integrated_resistance_pipeline.dir/build.make runtime/kernels/resistance/CMakeFiles/integrated_resistance_pipeline.dir/build
.PHONY : integrated_resistance_pipeline/fast

#=============================================================================
# Target rules for targets named clean_resistance_pipeline

# Build rule for target.
clean_resistance_pipeline: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean_resistance_pipeline
.PHONY : clean_resistance_pipeline

# fast build rule for target.
clean_resistance_pipeline/fast:
	$(MAKE) $(MAKESILENT) -f runtime/kernels/resistance/CMakeFiles/clean_resistance_pipeline.dir/build.make runtime/kernels/resistance/CMakeFiles/clean_resistance_pipeline.dir/build
.PHONY : clean_resistance_pipeline/fast

#=============================================================================
# Target rules for targets named test_bloom_filter

# Build rule for target.
test_bloom_filter: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_bloom_filter
.PHONY : test_bloom_filter

# fast build rule for target.
test_bloom_filter/fast:
	$(MAKE) $(MAKESILENT) -f runtime/kernels/resistance/CMakeFiles/test_bloom_filter.dir/build.make runtime/kernels/resistance/CMakeFiles/test_bloom_filter.dir/build
.PHONY : test_bloom_filter/fast

#=============================================================================
# Target rules for targets named minimizer_extraction

# Build rule for target.
minimizer_extraction: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 minimizer_extraction
.PHONY : minimizer_extraction

# fast build rule for target.
minimizer_extraction/fast:
	$(MAKE) $(MAKESILENT) -f runtime/kernels/profiler/CMakeFiles/minimizer_extraction.dir/build.make runtime/kernels/profiler/CMakeFiles/minimizer_extraction.dir/build
.PHONY : minimizer_extraction/fast

#=============================================================================
# Target rules for targets named fastq_processing

# Build rule for target.
fastq_processing: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fastq_processing
.PHONY : fastq_processing

# fast build rule for target.
fastq_processing/fast:
	$(MAKE) $(MAKESILENT) -f runtime/kernels/profiler/CMakeFiles/fastq_processing.dir/build.make runtime/kernels/profiler/CMakeFiles/fastq_processing.dir/build
.PHONY : fastq_processing/fast

#=============================================================================
# Target rules for targets named gpu_kmer_database

# Build rule for target.
gpu_kmer_database: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gpu_kmer_database
.PHONY : gpu_kmer_database

# fast build rule for target.
gpu_kmer_database/fast:
	$(MAKE) $(MAKESILENT) -f runtime/kernels/profiler/CMakeFiles/gpu_kmer_database.dir/build.make runtime/kernels/profiler/CMakeFiles/gpu_kmer_database.dir/build
.PHONY : gpu_kmer_database/fast

#=============================================================================
# Target rules for targets named gpu_profiler_pipeline

# Build rule for target.
gpu_profiler_pipeline: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gpu_profiler_pipeline
.PHONY : gpu_profiler_pipeline

# fast build rule for target.
gpu_profiler_pipeline/fast:
	$(MAKE) $(MAKESILENT) -f runtime/kernels/profiler/CMakeFiles/gpu_profiler_pipeline.dir/build.make runtime/kernels/profiler/CMakeFiles/gpu_profiler_pipeline.dir/build
.PHONY : gpu_profiler_pipeline/fast

#=============================================================================
# Target rules for targets named hierarchical_profiler_pipeline

# Build rule for target.
hierarchical_profiler_pipeline: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hierarchical_profiler_pipeline
.PHONY : hierarchical_profiler_pipeline

# fast build rule for target.
hierarchical_profiler_pipeline/fast:
	$(MAKE) $(MAKESILENT) -f runtime/kernels/profiler/CMakeFiles/hierarchical_profiler_pipeline.dir/build.make runtime/kernels/profiler/CMakeFiles/hierarchical_profiler_pipeline.dir/build
.PHONY : hierarchical_profiler_pipeline/fast

#=============================================================================
# Target rules for targets named hybrid_profiler_pipeline

# Build rule for target.
hybrid_profiler_pipeline: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hybrid_profiler_pipeline
.PHONY : hybrid_profiler_pipeline

# fast build rule for target.
hybrid_profiler_pipeline/fast:
	$(MAKE) $(MAKESILENT) -f runtime/kernels/profiler/CMakeFiles/hybrid_profiler_pipeline.dir/build.make runtime/kernels/profiler/CMakeFiles/hybrid_profiler_pipeline.dir/build
.PHONY : hybrid_profiler_pipeline/fast

#=============================================================================
# Target rules for targets named build_test_database

# Build rule for target.
build_test_database: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 build_test_database
.PHONY : build_test_database

# fast build rule for target.
build_test_database/fast:
	$(MAKE) $(MAKESILENT) -f runtime/kernels/profiler/CMakeFiles/build_test_database.dir/build.make runtime/kernels/profiler/CMakeFiles/build_test_database.dir/build
.PHONY : build_test_database/fast

#=============================================================================
# Target rules for targets named build_db_from_kmers

# Build rule for target.
build_db_from_kmers: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 build_db_from_kmers
.PHONY : build_db_from_kmers

# fast build rule for target.
build_db_from_kmers/fast:
	$(MAKE) $(MAKESILENT) -f runtime/kernels/profiler/CMakeFiles/build_db_from_kmers.dir/build.make runtime/kernels/profiler/CMakeFiles/build_db_from_kmers.dir/build
.PHONY : build_db_from_kmers/fast

#=============================================================================
# Target rules for targets named build_hierarchical_db

# Build rule for target.
build_hierarchical_db: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 build_hierarchical_db
.PHONY : build_hierarchical_db

# fast build rule for target.
build_hierarchical_db/fast:
	$(MAKE) $(MAKESILENT) -f runtime/kernels/profiler/CMakeFiles/build_hierarchical_db.dir/build.make runtime/kernels/profiler/CMakeFiles/build_hierarchical_db.dir/build
.PHONY : build_hierarchical_db/fast

#=============================================================================
# Target rules for targets named test_minimizer

# Build rule for target.
test_minimizer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_minimizer
.PHONY : test_minimizer

# fast build rule for target.
test_minimizer/fast:
	$(MAKE) $(MAKESILENT) -f runtime/kernels/profiler/CMakeFiles/test_minimizer.dir/build.make runtime/kernels/profiler/CMakeFiles/test_minimizer.dir/build
.PHONY : test_minimizer/fast

#=============================================================================
# Target rules for targets named test_fastq_pipeline

# Build rule for target.
test_fastq_pipeline: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_fastq_pipeline
.PHONY : test_fastq_pipeline

# fast build rule for target.
test_fastq_pipeline/fast:
	$(MAKE) $(MAKESILENT) -f runtime/kernels/profiler/CMakeFiles/test_fastq_pipeline.dir/build.make runtime/kernels/profiler/CMakeFiles/test_fastq_pipeline.dir/build
.PHONY : test_fastq_pipeline/fast

#=============================================================================
# Target rules for targets named debug_minimizer

# Build rule for target.
debug_minimizer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 debug_minimizer
.PHONY : debug_minimizer

# fast build rule for target.
debug_minimizer/fast:
	$(MAKE) $(MAKESILENT) -f runtime/kernels/profiler/CMakeFiles/debug_minimizer.dir/build.make runtime/kernels/profiler/CMakeFiles/debug_minimizer.dir/build
.PHONY : debug_minimizer/fast

#=============================================================================
# Target rules for targets named test_stats

# Build rule for target.
test_stats: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_stats
.PHONY : test_stats

# fast build rule for target.
test_stats/fast:
	$(MAKE) $(MAKESILENT) -f runtime/kernels/profiler/CMakeFiles/test_stats.dir/build.make runtime/kernels/profiler/CMakeFiles/test_stats.dir/build
.PHONY : test_stats/fast

#=============================================================================
# Target rules for targets named fastq_pipeline_debug

# Build rule for target.
fastq_pipeline_debug: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fastq_pipeline_debug
.PHONY : fastq_pipeline_debug

# fast build rule for target.
fastq_pipeline_debug/fast:
	$(MAKE) $(MAKESILENT) -f runtime/kernels/profiler/CMakeFiles/fastq_pipeline_debug.dir/build.make runtime/kernels/profiler/CMakeFiles/fastq_pipeline_debug.dir/build
.PHONY : fastq_pipeline_debug/fast

#=============================================================================
# Target rules for targets named test_hierarchical_db

# Build rule for target.
test_hierarchical_db: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_hierarchical_db
.PHONY : test_hierarchical_db

# fast build rule for target.
test_hierarchical_db/fast:
	$(MAKE) $(MAKESILENT) -f runtime/kernels/profiler/CMakeFiles/test_hierarchical_db.dir/build.make runtime/kernels/profiler/CMakeFiles/test_hierarchical_db.dir/build
.PHONY : test_hierarchical_db/fast

#=============================================================================
# Target rules for targets named test_synthetic

# Build rule for target.
test_synthetic: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_synthetic
.PHONY : test_synthetic

# fast build rule for target.
test_synthetic/fast:
	$(MAKE) $(MAKESILENT) -f runtime/kernels/profiler/CMakeFiles/test_synthetic.dir/build.make runtime/kernels/profiler/CMakeFiles/test_synthetic.dir/build
.PHONY : test_synthetic/fast

#=============================================================================
# Target rules for targets named test_real_fastq

# Build rule for target.
test_real_fastq: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_real_fastq
.PHONY : test_real_fastq

# fast build rule for target.
test_real_fastq/fast:
	$(MAKE) $(MAKESILENT) -f runtime/kernels/profiler/CMakeFiles/test_real_fastq.dir/build.make runtime/kernels/profiler/CMakeFiles/test_real_fastq.dir/build
.PHONY : test_real_fastq/fast

#=============================================================================
# Target rules for targets named test_fastq_pipeline_run

# Build rule for target.
test_fastq_pipeline_run: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_fastq_pipeline_run
.PHONY : test_fastq_pipeline_run

# fast build rule for target.
test_fastq_pipeline_run/fast:
	$(MAKE) $(MAKESILENT) -f runtime/kernels/profiler/CMakeFiles/test_fastq_pipeline_run.dir/build.make runtime/kernels/profiler/CMakeFiles/test_fastq_pipeline_run.dir/build
.PHONY : test_fastq_pipeline_run/fast

#=============================================================================
# Target rules for targets named test_database

# Build rule for target.
test_database: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_database
.PHONY : test_database

# fast build rule for target.
test_database/fast:
	$(MAKE) $(MAKESILENT) -f runtime/kernels/profiler/CMakeFiles/test_database.dir/build.make runtime/kernels/profiler/CMakeFiles/test_database.dir/build
.PHONY : test_database/fast

#=============================================================================
# Target rules for targets named test_hierarchical

# Build rule for target.
test_hierarchical: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_hierarchical
.PHONY : test_hierarchical

# fast build rule for target.
test_hierarchical/fast:
	$(MAKE) $(MAKESILENT) -f runtime/kernels/profiler/CMakeFiles/test_hierarchical.dir/build.make runtime/kernels/profiler/CMakeFiles/test_hierarchical.dir/build
.PHONY : test_hierarchical/fast

#=============================================================================
# Target rules for targets named test_hierarchical_real

# Build rule for target.
test_hierarchical_real: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_hierarchical_real
.PHONY : test_hierarchical_real

# fast build rule for target.
test_hierarchical_real/fast:
	$(MAKE) $(MAKESILENT) -f runtime/kernels/profiler/CMakeFiles/test_hierarchical_real.dir/build.make runtime/kernels/profiler/CMakeFiles/test_hierarchical_real.dir/build
.PHONY : test_hierarchical_real/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... analyze_resistance_profile"
	@echo "... benchmark_integrated"
	@echo "... build_clean_resistance_db"
	@echo "... build_integrated_resistance_db"
	@echo "... build_nucleotide_index"
	@echo "... build_protein_index"
	@echo "... build_resistance_catalog"
	@echo "... clinical_interpretation"
	@echo "... test_clean_pipeline"
	@echo "... test_database"
	@echo "... test_fastq_pipeline_run"
	@echo "... test_hierarchical"
	@echo "... test_hierarchical_real"
	@echo "... test_integrated_pipeline"
	@echo "... test_real_fastq"
	@echo "... test_synthetic"
	@echo "... validate_fq_database"
	@echo "... validate_integrated_db"
	@echo "... bloom_filter"
	@echo "... build_db_from_kmers"
	@echo "... build_hierarchical_db"
	@echo "... build_test_database"
	@echo "... clean_resistance_loader"
	@echo "... clean_resistance_pipeline"
	@echo "... debug_minimizer"
	@echo "... diagnostic_reporter"
	@echo "... enhanced_mutation_detection"
	@echo "... fastq_pipeline_debug"
	@echo "... fastq_processing"
	@echo "... fixed_database_loader"
	@echo "... fq_pipeline_gpu"
	@echo "... global_fq_mapper"
	@echo "... gpu_kmer_database"
	@echo "... gpu_profiler_pipeline"
	@echo "... hdf5_writer"
	@echo "... hierarchical_profiler_pipeline"
	@echo "... hybrid_profiler_pipeline"
	@echo "... integrated_resistance_pipeline"
	@echo "... kmer_screening"
	@echo "... minimizer_extraction"
	@echo "... resistance_detection_gpu"
	@echo "... sample_csv_parser"
	@echo "... test_bloom_filter"
	@echo "... test_fastq_pipeline"
	@echo "... test_hierarchical_db"
	@echo "... test_minimizer"
	@echo "... test_stats"
	@echo "... translated_search"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

