# Makefile for testing StreamingFnaProcessor

CXX = g++
NVCC = nvcc

# Compiler flags
CXXFLAGS = -std=c++17 -O2 -g -Wall -I. -I/usr/local/cuda/include
NVCCFLAGS = -std=c++17 -O2 -g -I. -I/usr/local/cuda/include

# CUDA libraries
CUDA_LIBS = -L/usr/local/cuda/lib64 -lcudart

# Target executable
TARGET = test_all_features_streaming

# Source files
SOURCES = test_all_features_streaming.cu \
          processing/genome_file_processor.cu

# Object files
OBJECTS = test_all_features_streaming.o \
          genome_file_processor.o

all: $(TARGET)

$(TARGET): $(OBJECTS)
	$(NVCC) $(NVCCFLAGS) -arch=sm_61 -o $@ $^ $(CUDA_LIBS)

test_all_features_streaming.o: test_all_features_streaming.cu
	$(NVCC) $(NVCCFLAGS) -arch=sm_61 -c -o $@ $<

genome_file_processor.o: processing/genome_file_processor.cu
	$(NVCC) $(NVCCFLAGS) -arch=sm_61 -c -o $@ $<

run: $(TARGET)
	./$(TARGET) ../../../../data/test_50_genomes.fna

clean:
	rm -f $(OBJECTS) $(TARGET)

.PHONY: all run clean