#!/bin/bash
# Full integration test with HDF5 libraries installed

echo "============================================"
echo "BioGPU Full Integration Test"
echo "============================================"
echo ""

# Create more realistic test data
mkdir -p /tmp/biogpu_full_test/{input,output,databases}

echo "Creating test FASTQ files..."
# Create slightly larger test files
cat > /tmp/biogpu_full_test/input/test_R1.fastq.gz << 'EOF'
@M00001:1:000000000-AAAAA:1:1101:10000:1000 1:N:0:1
ACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGT
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@M00001:1:000000000-AAAAA:1:1101:10000:2000 1:N:0:1
TGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCA
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@M00001:1:000000000-AAAAA:1:1101:10000:3000 1:N:0:1
ATGCCCGCGGGAATTCGAATTCCCGCGGGC